name: Deploy Nodejs app to AWS EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t bennyhinnbezawada/campus-connect-backend:latest .
      - name: Push Docker Image
        run: docker push bennyhinnbezawada/campus-connect-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: docker pull bennyhinnbezawada/campus-connect-backend:latest
      - name: Stop Existing Container
        run: docker stop campus-connect-backend || true
      - name: Remove Existing Container
        run: docker rm campus-connect-backend || true
      - name: Run New Container
        run: |
         docker run -d -p 3101:3101 \
         --name campus-connect-backend \
         --env-file /home/ubuntu/.env \
         --restart unless-stopped \
          bennyhinnbezawada/campus-connect-backend:latest